title: Oskar Martin Kieliger # your name (or website title) here
logo: "images/download (4).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  it's me, hi. I'm the problem it's me
  
  <!-- Font Awesome 5.15.1 CSS -->
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css'>


  <br><br>
  <a href="https://github.com/oskarmk/oskarmk.github.io/tree/main/pdf/Oskar Martin Resume EN.pdf" class="fa-solid fa-file-lines" target="blank_">  CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/oskarmartin/" class="fab fa-brands fa-linkedin" target="blank_">  LinkedIn</a>
  <br><br>
  <a href="https://chusikowski.substack.com/" class="fa-solid fa-newspaper" target="blank_">  Substack</a>
  <br><br>
  <a href="https://github.com/oskarmk" class="fa-brands fa-square-github" target="blank_">  Github</a>
  <br><br>
  <a href="https://www.instagram.com/zmadh.art/" class="fa-brands fa-square-instagram" target="blank_">  AI Art</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

 
