title: Oskar Martin Kieliger # your name (or website title) here
logo: "download (4).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  it's me, hi. I'm the problem it's me

  <br><br>
  <a href="https://www.linkedin.com/in/oskarmartin/">LinkedIn</a>
  <br><br>
  <a href="https://chusikowski.substack.com/">Substack</a>
  <br><br>
  <a href="https://github.com/oskarmk">Github</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

 
