title: Oskar Martin Kieliger # your name (or website title) here
logo: "download (4).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  it's me, hi. I'm the problem it's me

  <br><br>
  <a href="https://www.linkedin.com/in/oskarmartin/">LinkedIn Profile</a>
  <br><br>
  <a href="https://chusikowski.substack.com/">View My Newsletter</a>
  <br><br>
    <a href="https://in.linkedin.com/in/raru-chempazhanthy-43549623" class="social-icon si-rounded si-small si-linkedin" target="_blank">
    <i class="icon-linkedin"></i>
    <i class="icon-linkedin"></i>
 </a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

 
