title: Oskar Martin # your name (or website title) here
logo: "images/download (4).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer with a strong emphasis in Robotic Process Automation (RPA) and a broad expertise in machine learning. Demonstrated success in developing and implementing RPA solutions to revitalize and automate outdated business processes, significantly increasing operational efficiency. Proficient in applying various machine learning methodologies to drive data-driven decision-making and enhance process automation capabilities. 
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">

  <br><br>
  <a href="https://www.linkedin.com/in/oskarmartin/" class="fab fa-brands fa-linkedin" target="blank_">   LinkedIn</a>
  <br><br>
  <a href="https://chusikowski.substack.com/" class="fa-solid fa-newspaper" target="blank_">    Substack</a>
  <br><br>
  <a href="https://www.instagram.com/zmadh.art/" class="fa-brands fa-instagram" target="blank_">    AI Art</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
