title: Oskar Martin Kieliger # your name (or website title) here
logo: "images/download (4).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  it's me, hi. I'm the problem it's me


<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <br><br>
  <a href="https://www.linkedin.com/in/oskarmartin/" class="fa fa-facebook" target="blank_">LinkedIn</a>
  <br><br>
  <a href="https://chusikowski.substack.com/" target="blank_">Substack</a>
  <br><br>
  <a href="https://github.com/oskarmk" target="blank_">Github</a>
  <br><br>
  <a href="https://github.com/oskarmk/oskarmk.github.io/tree/main/pdf/Oskar Martin Resume EN.pdf" target="blank_">CV</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

 
